INSERT INTO states
    (state_namename, state_abbreviation, region, population)
VALUES
    ('California', 'CA', 'West', 39.51),
    ('Colorado', 'CO', 'West', 5.76),
    ('Connecticut', 'CT', 'Northeast', 3.57),
    ('Delaware', 'DE', 'Northeast', 0.98),
    ('Florida', 'FL', 'South', 21.48),
    ('Georgia', 'GA', 'South', 10.62),
    ('Hawaii', 'HI', 'West', 1.42),
    ('Idaho', 'ID', 'West', 1.75),
    ('Illinois', 'IL', 'Midwest', 12.67),
    ('Indiana', 'IN', 'Midwest', 6.73),
    ('Iowa', 'IA', 'Midwest', 3.16),
    ('Kansas', 'KS', 'Midwest', 2.91),
    ('Kentucky', 'KY', 'South', 4.47),
    ('Louisiana', 'LA', 'South', 4.65),
    ('Maine', 'ME', 'Northeast', 1.35),
    ('Maryland', 'MD', 'Northeast', 6.05),
    ('Massachusetts', 'MA', 'Northeast', 6.89),
    ('Michigan', 'MI', 'Midwest', 10.00),
    ('Minnesota', 'MN', 'Midwest', 5.64),
    ('Mississippi', 'MS', 'South', 2.98),
    ('Missouri', 'MO', 'Midwest', 6.14),
    ('Montana', 'MT', 'West', 1.06),
    ('Nebraska', 'NE', 'Midwest', 1.93),
    ('Nevada', 'NV', 'West', 3.08),
    ('New Hampshire', 'NH', 'Northeast', 1.36),
    ('New Jersey', 'NJ', 'Northeast', 8.88),
    ('New Mexico', 'NM', 'West', 2.09),
    ('New York', 'NY', 'Northeast', 19.45),
    ('North Carolina', 'NC', 'South', 10.49),
    ('North Dakota', 'ND', 'Midwest', 0.76),
    ('Ohio', 'OH', 'Midwest', 11.69),
    ('Oklahoma', 'OK', 'South', 3.96),
    ('Oregon', 'OR', 'West', 4.22),
    ('Pennsylvania', 'PA', 'Northeast', 12.80),
    ('Rhode Island', 'RI', 'Northeast', 1.06),
    ('South Carolina', 'SC', 'South', 5.15),
    ('South Dakota', 'SD', 'Midwest', 0.89),
    ('Tennessee', 'TN', 'South', 6.83),
    ('Texas', 'TX', 'South', 28.99),
    ('Utah', 'UT', 'West', 3.21),
    ('Vermont', 'VT', 'Northeast', 0.63),
    ('Virginia', 'VA', 'South', 8.54),
    ('Washington', 'WA', 'West', 7.61),
    ('West Virginia', 'WV', 'South', 1.80),
    ('Wisconsin', 'WI', 'Midwest', 5.82),
    ('Wyoming', 'WY', 'West', 0.58);
